config/routes.rb
Lesson::Application.routes.draw do
  devise_for :users
    
    
  resources :chapters

  resources :courses

  root 'home#index'
  
  
  
  namespace :cpanel do
    root :to => 'home#index'
    resources :courses
    resources :chapters
  end

  

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to  :course
  before_save :markdown_for_body_html
  
  
  
  def markdown_for_body_html
    #return true if not self.body_changed?
    self.body_html = MarkdownConverter.convert(self.body)
  rescue => e
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :chapters,:counter_cache=>true
  validates :name, :length=>{:in => 3..20,:message=>"课程名称长度请在3~20个汉字之间"}
  
  mount_uploader :cover,PhotoUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable,:lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  def render_404
    render_optional_error_file(404)
  end

  def render_403
    render_optional_error_file(403)
  end

  def render_optional_error_file(status_code)
    status = status_code.to_s
    if ["404","403", "422", "500"].include?(status)
      render :template => "/errors/#{status}", :format => [:html], :handler => [:erb], :status => status, :layout => "application"
    else
      render :template => "/errors/unknown", :format => [:html], :handler => [:erb], :status => status, :layout => "application"
    end
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.paginate :page=>params[:page],:per_page=>8    
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @chapter }
      else
        format.html { render action: 'new' }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to cpanel_chapters_url, notice: 'Chapter was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to cpanel_chapters_url, notice: "Chapter #{@chapter.title} was successfully updated." } 
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:title, :body, :body_html, :course_id,:video_url,
                      :download_url,:publish,:duration,:description)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.paginate :page=>params[:page],:order=>'created_at desc', :per_page =>10
    
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to cpanel_courses_url, notice: "Course #{@course.name} was successfully updated." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :content, :author,:cover)
    end
end

app/controllers/cpanel/application_controller.rb
# coding: utf-8
class Cpanel::ApplicationController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!
  before_filter :require_admin

  def require_admin
    if not current_user.admin?
      render_404
    end
  end
  
end

app/controllers/cpanel/chapters_controller.rb
class Cpanel::ChaptersController < Cpanel::ApplicationController
  layout "admin"
  
  def index
    @chapters = Chapter.paginate :page=>params[:page],:per_page=>10    
  end
end

app/controllers/cpanel/courses_controller.rb
class Cpanel::CoursesController < Cpanel::ApplicationController
  layout "admin"
  def index
    @courses = Course.paginate :page=>params[:page],:order=>'created_at desc', :per_page =>10
  end
  
end

app/controllers/cpanel/home_controller.rb
class Cpanel::HomeController < Cpanel::ApplicationController
  layout "admin"
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(str, options = {})
    # XXX: the renderer instance should be a class variable

    options[:hard_wrap] ||= false
    options[:class] ||= ''
    assembler = Redcarpet::Render::HTML.new(:hard_wrap => options[:hard_wrap]) # auto <br> in <p>

    renderer = Redcarpet::Markdown.new(assembler, {
      :autolink => true,
      :fenced_code_blocks => true
    })
    content_tag(:div, raw(MarkdownConverter.convert(str)), :class => options[:class])
  end
  
  
  def meta_tag(name, value)
    %(<meta name="#{name}" content="#{Rack::Utils.escape_html(value)}"/>).html_safe
  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/cpanel/chapters_helper.rb
module Cpanel::ChaptersHelper
end

app/helpers/cpanel/courses_helper.rb
module Cpanel::CoursesHelper
end

app/helpers/cpanel/home_helper.rb
module Cpanel::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/chapters/_chapter.html.erb
<div class="row-fluid course_item">
	<div class="span12">
		<h2><%= link_to chapter.title,chapter,:method=>:get%>
		</h2>
	</div>
	<div class="row-fluid">
		<%=chapter.description %>
	</div>
</div>

app/views/chapters/_form.html.erb
<%= simple_form_for(@chapter,:html=>{:class=>"form-horizontal"}) do |f| %>
<%= render "shared/error_messages",:target=>@chapter%>

 <fieldset>
	<legend>章节信息</legend>
</fieldset>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description,rows: 10, cols: 80 %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body,rows: 10, cols: 80 %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :video_url %><br>
    <%= f.text_field :video_url %>
  </div>
  <div class="field">
    <%= f.label :download_url %><br>
    <%= f.text_field :download_url %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :publish %><br>
    <%= f.check_box :publish %>
  </div>
  <div class="actions">
    
    	<%= f.submit "提交", :class => "btn btn-primary" %>
	 <%= link_to '返回', courses_path ,:class => "btn"%>

  </div>
<% end %>

app/views/chapters/edit.html.erb
<h2>编辑章节</h2>
<%= render 'form' %>

app/views/chapters/index.html.erb
<div class="hero-unit">
	<h1>章节浏览</h1>
</div>
    <% @chapters.each do |chapter| %>
 		<%=render :partial=> chapter%>
    <% end %>

<%= will_paginate @chapters%>

<br>

app/views/chapters/new.html.erb
<h2>创建章节</h2>

<%= render 'form' %>

<%= link_to 'Back', chapters_path %>

app/views/chapters/show.html.erb
<% content_for :head do %>
  <%= meta_tag('chapter-url', @chapter.video_url) %>
<% end %>




<div class="row-fluid">
	<div class="row-fluid">

		<div class="span4">
			<ul class="nav nav-tabs" id="myTab">
			  <li class="active"><a href="#home">章节信息</a></li>
			  <li><a href="#profile">讲解</a></li>
			  <li><a href="#messages">问题</a></li>
			</ul>

			<div class="tab-content">
			  <div class="tab-pane active" id="home">
		  			<h4><%=@chapter.course.name%></h4>
		 			<h5><%= @chapter.title %></h5>	
					<%=@chapter.description%>
			  </div>
			  <div class="tab-pane" id="profile">
				  	<%=raw @chapter.body_html %>
			  </div>
			  <div class="tab-pane" id="messages">...</div>
			</div>
		</div>
		<div class="span8">
			<%= render "shared/video_player"%>
		</div>
	</div>
</div>

app/views/courses/_form.html.erb
<%= simple_form_for(@course,:html=>{:class=>"form-horizontal"}) do |f| %>

	<%= render "shared/error_messages",:target=>@course%>

  <fieldset>
	<legend>课程封面</legend>
 </fieldset>

	<%if @course.cover?%>
	<%= image_tag @course.cover,:class=>"course_icon"%>
	<%else%>
	<%= image_tag ('wrong.png')%>
	<%end%>
	 <div class="control-group">
	    <div class="controls">
	    <%= f.input :cover%>
	    </div>
	</div>

  <fieldset>
	<legend>课程基本信息</legend>
 </fieldset>


 <div class="control-group">
    <%= f.label :name,:class=>"control-label" %>
    <div class="controls">
    <%= f.text_field :name %>
    </div>
</div>
<div class="control-group">
    <%= f.label :author,:class=>"control-label" %>
    <div class="controls">
    <%= f.text_field :author %>
  </div>
</div>
 <div class="control-group">
    <%= f.label :description,:class=>"control-label"%>
    <div class="controls">
    <%= f.text_field :description %>
	</div>
</div>
 <div class="control-group">
    <%= f.label :content,:class=>"control-label"%>
    <div class="controls">
    <%= f.text_area :content %>
	</div>
</div>
<div class="control-group">
	<div class="controls">
    	<%= f.submit "提交", :class => "btn btn-primary" %>
        <%= link_to '返回', courses_path ,:class => "btn"%>
  	</div>
</div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<div class="hero-unit">
	<h1><%=t 'courses.show_title'%></h1>
</div>

<div class="container span8 course_container">
	<% @courses.each_with_index do |course,i| %>
	<%=render :partial=>course%>
<% end %>
</div>
<div class="span8 offset2">
	<%= will_paginate @course%>
</div>

app/views/courses/new.html.erb
<h1><%=t("courses.title")%></h1>
<%= render 'form' %>

app/views/courses/show.html.erb
<div class="hero-unit">
	<h1> <%= @course.name %></h1>
	<small><%=@course.description %></small>	
	<p class="text-info">
		<%= raw @course.content %>
	</p>
	<p class="text-info">作者:<%= @course.author %>
  </p>
</div>


<%if @course.chapters.count%>
<div class="span8">
	<h2>章节信息</h2>
	
<% @course.chapters.each do |chapter| %>
	<%=render 'chapters/chapter' ,:chapter=>chapter%>
<% end %>

<%else%>
<div class="alert">
  	 暂无相应章节信息
</div>
<%end%>
</div>

app/views/cpanel/chapters/_chapter.html.erb
<tr>
	<td><%=chapter.id%></td>	
	<td><%= link_to chapter.title,edit_chapter_path(chapter),:method=>:get%></td>	
	<td><%= chapter.duration%></td>
	<td><%= chapter.created_at%><br>
	<% if chapter.publish%>
	<%='已发布'%>
	<%else%>
	<%='草稿'%>
	<%end%>
	</td>
	<td>
		<div class="btn-group">
		  <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
		    操作
		    <span class="caret"></span>
		  </a>
		  <ul class="dropdown-menu">
		  	<li><%=link_to '编辑',edit_chapter_path(chapter)%></li>
		  	<li><%=link_to '删除',chapter_path(chapter),:method=>:delete,:confirm => "OK?"%></li>
			
		  </ul>
		</div>
	</td>
	
</tr>

app/views/cpanel/chapters/index.html.erb
<div class="hero-unit">
	<h1>章节浏览</h1>
</div>

<table class="table table-hover  table-striped">
	<thead>
	<tr>	
		<th>#</th>
		<th>标题</th>
		<th>视频时间</th>
		<th>创建日期</th>
		<th>动作</th>
		
	</tr>
	</thead>
	<tbody>
	<% @chapters.each do |chapter| %>
 		<%=render :partial=> chapter%>
    <% end %>
	</tbody>
</table>
<%= will_paginate @chapters%>



<br>

app/views/cpanel/courses/_course.html.erb
<div class="course_item row-fluid">
	<div class="row-fluid">
		<div class="course_admin_action">
			<div class="btn-group">
		  <%= link_to '编辑', edit_course_path(course),:class=>'btn' %>
		  <%= link_to '删除', course,:class=>'btn btn-danger',method: :delete, data: { confirm: 'Are you sure?' } %>
			</div>
		</div>
		<div class="span2 fl">
			<%if course.cover?%>
			<%= image_tag course.cover,:class=>"course_icon"%>
			<%else%>
			<%= image_tag ('wrong.png')%>
			<%end%>
		</div>
		<div class="class_info fl">
			<h3><%= link_to course.name, course %></h3>
			<p class="p_intro">简介：<%= course.description %></p>
		</div>	
	</div>
	<div class="row-fluid">
		<div class="course_user_action">
			<span class="badge badge-info">
		共有<%=course.chapters.count%>课</span>
		</div>
	</div>
</div>

app/views/cpanel/courses/index.html.erb
<div class="hero-unit">
	<h1>课程管理</h1>
</div>
<div class="container span8 course_container">
	<% @courses.each_with_index do |course,i| %>
	<%=render :partial=>course%>
<% end %>
</div>
<div class="span8">
	<%= will_paginate @course%>
</div>

app/views/cpanel/home/index.html.erb
<div class="hero-unit">
	<h1>管理员工具</h1>
</div>
<div>
	<%= render_cell :courses,:index_section%>
</div>

app/views/home/index.erb
<div id='container'>
	<div class="hero-unit">
	  <h1>首页</h1>
	  <p>Welcome to my home page</p>
	  <p>
		<%=button_to '了解更多课程',:courses,:class=>"btn btn-primary btn-large",:method=>'get'%>

	  </p>
	</div>
	</div>
	<%= render_cell :courses,:index_section%>
	</div>
</div>

app/views/home/index.html.erb
<div class="hero-unit">
	<h1>玩电脑游戏，不如做游戏</h1>
	 <p>从今天开始零起点学习编程！面向9岁以上的计算编教程。</p><p>对您的孩子来说，您的陪伴才是他们学习的动力，陪伴孩子学习可以取得更佳的效果！</p>
		<%=button_to '了解更多课程',:courses,:class=>"btn btn-primary btn-large",:method=>'get'%>
</div>

<!--div class="content_container">
	<%= render_cell :courses,:index_section%>
</div-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lesson</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container root_container">

	<div class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
				<ul class="nav">
					<li><%= link_to("首页",root_path)%></li>
					<li><%= link_to("课程",courses_path)%></li>
					<li><%= link_to("章节",chapters_path)%>
				</ul>
				<ul class="nav pull-right">
					<% if current_user %>
						<% if current_user.admin %>		
					<li><%=link_to("管理" ,cpanel_root_path,:method=>:get)%></li>
						<%end%>
				
				
					<li><%=link_to("登出" ,destroy_user_session_path,:method=>:delete)%></li>
					<%else%>
					<li><%= link_to("登陆",new_user_session_path,:method=>:get)%></li>
					
					<%end%>
                </ul>
			</div>
		</div>
	</div>
	
	<div class="container">
		
		<div class="container-fluid">
		  <div class="row-fluid">
		    <div class="span2">		    
		    	<ul class="nav nav-list">
				  <li class="nav-header">管理工具首页</li>
					<li><%=link_to("管理工具首页",cpanel_root_path)%></li>
		        	<li class="nav-header">课程信息管理</li>
		          	<li>	<%=link_to("课程管理",cpanel_courses_path)%></li>
		          	<li>	<%=link_to("新建课程",new_course_path)%></li>
		          	<li>	<%=link_to("章节管理",cpanel_chapters_path)%></li>
		          	<li>	<%=link_to("新建章节",new_chapter_path)%></li>
		
		
		        </ul>
			</div>
		    <div class="span10">
				<%if notice%>
				<div class="alert alert-info">
					<a class="close" data-dismiss='alert' href="#">x</a>
				<p id="notice"><%= notice %></p>
				</div>
				<%end%>
				<%=yield%>
			</div>
		  </div>
		</div>
	</div>
	</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lesson</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield :head%>
</head>
<body>
	<div class="container root_container">
		<div class="navbar navbar-fixed-top navbar-inverse">
			<div class="navbar-inner">
				<div class="container">
					<ul class="nav">
						<li><%= link_to("首页",root_path)%></li>
						<li><%= link_to("课程",courses_path)%></li>
						<!--<li><%= link_to("章节",chapters_path)%> -->
					</ul>
					<ul class="nav pull-right">
						<% if current_user %>
							<% if current_user.admin %>
							<li><%=link_to("管理" ,cpanel_root_path,:method=>:get)%></li>
							<%end%>
							<li><%=link_to("登出" ,destroy_user_session_path,:method=>:delete)%></li>
							<%else%>
							<li><%= link_to("登陆",new_user_session_path,:method=>:get)%></li>
							<%end%>
                		</ul>
					</div>
				</div>
			</div>
	
		<div class="container">
			<%if notice%>
			<div class="alert alert-info">
				<a class="close" data-dismiss='alert' href="#">x</a>
				<p id="notice"><%= notice %></p>
			</div>
			<%end%>
			<%= yield %>
		</div>
	</div>
		
		<footer class="footer">
				<ul>
					<li>About</li>
					<li>关注我们的微博</li>
				</ul>
		</footer>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
	<div class="alert alert-block alert-error">
		<a class="close" data-dismiss='alert' href="#">x</a>
		<p><strong>有<%=@course.errors.count%>处问题导致无法提交:</strong></p>
    <% target.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_video_player.erb
<div id="jp_container_1" class="jp-video">
  <div class="jp-type-single">
    <div id="jquery_jplayer_1" class="jp-jplayer"></div>
    <div class="jp-gui">
	
		<div class="jp-video-play">
			<a href="javascript:;" class="jp-video-play-icon" tabindex="1">play</a>
		</div>

	
      <div class="jp-interface">
        <div class="jp-progress">
          <div class="jp-seek-bar">
            <div class="jp-play-bar"></div>
          </div>
        </div>
        <div class="jp-current-time"></div>
        <div class="jp-duration"></div>
        <div class="jp-controls-holder">
          <ul class="jp-controls">
            <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
            <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
            <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
            <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
            <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
            <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
          </ul>
          <div class="jp-volume-bar">
            <div class="jp-volume-bar-value"></div>
          </div>
          <ul class="jp-toggles">
            <li><a href="javascript:;" class="jp-full-screen" tabindex="1" title="full screen">full screen</a></li>
            <li><a href="javascript:;" class="jp-restore-screen" tabindex="1" title="restore screen">restore screen</a></li>
            <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
            <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="jp-no-solution">
      <span>Update Required</span>
      To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
    </div>
  </div>
</div>